### pytorch张量及其创建
- 在神经网络中第一步就是对数据进行预处理
- 预处理的目的就是为了将我们拿到的数据转换成能被神经网络感知的张量

#### 创建张量
- pytorch提供四种方式创建张量
- 工厂函数：接受参数输入并返回特定类型对象的函数；dtype
- 通常情况下会更倾向于选择工厂函数

In [215]:
import torch
import numpy as np
import random
random.seed(42)
# 创建张量
t = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 创建一个ndarray
print(torch.Tensor(t))           # 类构造函数
print(torch.tensor(t))           # 工厂函数
print(torch.as_tensor(t))        # 工厂函数
print(torch.from_numpy(t))       # 工厂函数

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


#### 4种创建张量的区别1 - 数据类型


In [216]:
data = np.array([1,2,3])
t1 = torch.Tensor(data)
print(t1)
print(t1.dtype)
t2 = torch.tensor(data)
print(t2)
print(t2.dtype)
t3 = torch.as_tensor(data)
print(t3)
print(t3.dtype)
t4 = torch.from_numpy(data)
print(t4)
print(t4.dtype)

tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3])
torch.int64
tensor([1, 2, 3])
torch.int64
tensor([1, 2, 3])
torch.int64


- 使用类构造函数和工厂函数后生成的数据类型不同，主要原因是：构造函数在构造一个张量时使用全局缺省值，而工厂函数通过输入数据的类型来推断输出数据的类型
- 通过torch.get_default_dtype 获得全局默认数据类型

In [217]:
print("default type ",torch.get_default_dtype())

default type  torch.float32


- 显示指定数据类型

In [ ]:
t = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
t

 #### 四种方法的区别2：数据分配内存方式

In [226]:
data = np.array([1,2,3])
print(data)
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)
print(t1,t2,t3,t4)

# update value in data, all elements to 0s
data[1]=0
data[2]=0
# t1 和 t2 输出的都是更改前的数组
print(t1)
print(t2)
# t3 和 t4 输出的都是更改后的数组
print(t3)
print(t4)
print('********')
data[2] = 12.2
print(data)
print(t3)
print(t4)


[1 2 3]


TypeError: expected np.ndarray (got list)

- 上述差异由创建tensor时内存分配造成。
- t1 t2在创建时会复制数组中的元素到内存，因此改变data的值不会影响tensor
- t3 t4数据与data内存共享，因此当元数据被修改后t3 t4同样被修改
- 我们可以将t1 t2 当做“值传递”，t3 t4当做“引用传递”
- 数据共享比数据拷贝更加高效

#### np->tensor最佳转换方式
- 数据拷贝最佳方式 - torch.tensor()
- 数据共享最佳方式 - torch.as_tensor()，因为as_tensor()可接收任意类型的参数，而from_numpy只接收ndarray类型的数据
  

#### 其他方式创建Tensor

In [232]:
# 单位张量的创建(二维),dtype=torch.float)
eye = torch.eye(4,3,dtype=torch.float)
print(eye)
#全零张量的创建（二维）
zeros = torch.zeros_like(eye)
print(zeros)
#全1张量的创建(二维)
ones = torch.ones(4,5) 
print(ones )

ar = torch.arange(1,10,2)
print(ar)

int_t = torch.randint(0,20,(3,3,2))
print(int_t)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([1, 3, 5, 7, 9])
tensor([[[ 3,  7],
         [16,  6],
         [18, 10]],

        [[16,  3],
         [11, 17],
         [ 6, 14]],

        [[ 3,  2],
         [19, 17],
         [ 8, 12]]])


### Tensor属性

In [240]:
# 创建一个 Tensor
tensor = torch.randn(3, 4)
print(tensor)
# 查看 Tensor 的形状
print(tensor.shape)  # (3, 4)

# 查看 Tensor 的数据类型
print(tensor.dtype)  # torch.float32

# 查看 Tensor 所在的设备
print(tensor.device)  # cpu

# 查看 Tensor 的维度数
print(tensor.ndim)  # 2

# 查看 Tensor 中元素的总数
print(tensor.numel())  # 12

# 查看 Tensor 是否需要梯度计算
print(tensor.requires_grad)  # False
print(tensor.grad)


n = np.random.randn(300,400)
print(n.mean())

t = torch.randn(300,400)

print(t.mean().add(2))

tensor([[ 0.6812, -0.8365, -0.2817,  0.5858],
        [ 0.6637,  1.0637, -0.0299,  1.2013],
        [ 1.2485,  1.2558, -0.3473, -0.1321]])
torch.Size([3, 4])
torch.float32
cpu
2
12
False
None
0.004718895156095535
tensor(1.9975)


#### 数值类型:

- 浮点数:
    - torch.float32: 32 位浮点数，通常用于存储实数数据。
    - torch.float64: 64 位浮点数，通常用于存储高精度实数数据。
- 整数:
    - torch.int8: 8 位整数，通常用于存储较小的整数数据。
    - torch.int16: 16 位整数，通常用于存储中等大小的整数数据。
    - torch.int32: 32 位整数，通常用于存储较大的整数数据。
    - torch.int64: 64 位整数，通常用于存储高精度整数数据


- 选择数据类型时，应考虑以下因素:

    - 精度: 所需的精度决定了应使用哪种数据类型。例如，如果要进行科学计算，则需要使用高精度数据类型，例如 torch.float64。
    - 存储空间: 不同数据类型占用不同的存储空间。例如，torch.float64 数据类型占用比 torch.float32 数据类型更多的存储空间。
    - 计算效率: 不同数据类型具有不同的计算效率。例如，torch.float32 数据类型的计算效率通常高于 torch.float64 数据类型。
- 常用的数据类型
    - 图像: 通常使用 torch.uint8 数据类型存储图像，因为每个像素值介于 0 和 255 之间。
    - 文本: 通常使用 torch.string 数据类型存储文本。
    - 实数: 通常使用 torch.float32 数据类型存储实数，因为它具有足够的精度和计算效率。

### Tensor的操作
- 常见的张量操作类型
    - Reshaping operations    -- 重塑
    - Element-wise operations -- 元素级操作
    - Reduction operations    -- 缩减操作
    - Access operations       -- 访问操作

#### Reshaping operations
- 重塑是Tensor最重要的操作之一， 通过张量的重塑我们可以将数据转换为符合特定要求的操作。例如在卷积神经网络中，需要将输入图像reshape成适合卷积操作的形状。


In [48]:
t = torch.tensor([[1,1,1,1],
                 [2,2,2,2],
                  [3,3,3,3]], dtype=torch.float32)
# print(t.size())
# 获得张量形状(3,4)
print(t.shape) 

# 获得tensor的元素个数
print(torch.tensor(t.shape).prod())
print(t.numel())



torch.Size([3, 4])
tensor(12)
12


#### Reshape
- 有时候我们想要彻底改变张量的形状，但同时仍然保留元素的数量及其内容。
- 这种情况一般会在CNN模型的卷积层和模型的线性层之间的接口处
- 这在图像分类模型中很常见。卷积核将产生 x 宽度 y高度的输出张量，但后面的线性层需要一维输入。reshape()便可以执行该操作



In [242]:
t = torch.rand(3,28,28)
print(t.shape)

t1 = t.reshape(3*28*28) #
print(t1.shape)

t2 = torch.reshape(t1,(3,28,28))
print(t2.shape)


torch.Size([3, 28, 28])
torch.Size([2352])
torch.Size([3, 28, 28])


#### squeeze/unsqueeze
- squeeze/unsqueeze用来修改张量维度数
- 

In [258]:
# unqueeze
# 假设存在一个表示图片信息的张量(3,28,28).此时模型需要输入批次信息，那么我们可以使用unsequeeze方式来新增一个批次维度
t = torch.rand(3,28,28)
 
t1 = torch.unsqueeze(t,-4) # torch.unsqueeze(t,1/2/3) 
print(t1.shape)
print(t1.shape)
t2=torch.unsqueeze(t1,-4) # torch.unsqueeze(t,1/2/3) 
print(t2.shape)
# 通过unsqueeze(t,0) 在原始张量新增了一个维度 第0维
# 维度的新增不会改变张量元素个数

torch.Size([1, 3, 28, 28])
torch.Size([1, 3, 28, 28])
torch.Size([1, 1, 3, 28, 28])


In [264]:
# squeeze
# 假如模型返回的数据是[1,10]的矩阵数据，但是我们期望的返回是一个只有10个数字的一维向量。 此时，我们可以通过sequeeze()方法来实现。去删掉一个长度为1的秩删掉

t = torch.rand(2,3,10)
print(t.shape)
print(t)

t1 = torch.squeeze(t,1) # 如果不给index， 则会将所有长度为1的秩删掉
print(t1.shape)
print(t1)

#

torch.Size([2, 3, 10])
tensor([[[2.3860e-01, 6.2105e-01, 8.8141e-01, 3.3826e-01, 3.4979e-01,
          1.8168e-01, 2.0700e-01, 8.8389e-01, 5.4165e-01, 6.7819e-01],
         [3.7341e-02, 2.2192e-01, 8.7680e-01, 5.4235e-01, 3.5240e-01,
          7.4247e-01, 7.3136e-01, 4.4930e-01, 1.3222e-01, 8.9691e-01],
         [1.2803e-01, 1.9953e-01, 9.6692e-01, 3.9269e-01, 6.3754e-01,
          8.8554e-01, 6.6381e-01, 9.6527e-02, 4.7500e-02, 3.4489e-01]],

        [[7.8327e-01, 5.9071e-01, 3.2326e-01, 4.0202e-01, 7.9513e-01,
          2.4478e-01, 4.9333e-01, 3.7004e-01, 5.9928e-01, 5.1452e-01],
         [8.5287e-01, 8.4385e-03, 7.4425e-01, 2.6430e-01, 8.3342e-01,
          8.9788e-01, 8.2888e-01, 7.8374e-01, 8.9340e-01, 4.5597e-01],
         [4.1275e-01, 4.6898e-01, 7.1635e-01, 5.8191e-01, 4.6249e-02,
          1.9194e-01, 5.3408e-01, 8.2432e-01, 8.4030e-01, 2.6900e-04]]])
torch.Size([2, 3, 10])
tensor([[[2.3860e-01, 6.2105e-01, 8.8141e-01, 3.3826e-01, 3.4979e-01,
          1.8168e-01, 2.0700e-01, 

#### flatten
- flatten张量：除去所有的轴，只保留一个，创造一个单轴张量包含原张量所有元素；
- flatten操作是从一个卷积层过度到一个全连接层时在神经网络中必须发生的；
- flatten操作是一种特殊的reshaping操作，即所有轴被挤压成一个轴
- flatten操作的前提：张量至少有两个轴

In [270]:
t = torch.rand(2,2,2)
print(t)
# flatten
t_flatten = torch.flatten(t)
print(t_flatten.shape)
print(t_flatten)
# reshape
t_reshape =  t.reshape(t.numel())
print(t_reshape.shape)
print(t_reshape)
# reshape  -1 
t_reshape_1 =  t.reshape(-1)
print(t_reshape_1.shape)
print(t_reshape_1)

t_view= t.view(t.numel())
print(t_view)

tensor([[[0.4137, 0.7878],
         [0.0748, 0.8946]],

        [[0.7580, 0.3687],
         [0.8001, 0.2260]]])
torch.Size([8])
tensor([0.4137, 0.7878, 0.0748, 0.8946, 0.7580, 0.3687, 0.8001, 0.2260])
torch.Size([8])
tensor([0.4137, 0.7878, 0.0748, 0.8946, 0.7580, 0.3687, 0.8001, 0.2260])
torch.Size([8])
tensor([0.4137, 0.7878, 0.0748, 0.8946, 0.7580, 0.3687, 0.8001, 0.2260])
tensor([0.4137, 0.7878, 0.0748, 0.8946, 0.7580, 0.3687, 0.8001, 0.2260])


#### 转置
- PyTorch 中的转置操作用于改变张量的维度顺序，这在卷积、矩阵乘法都可能被使用到。
- torch.transpose() 
- t()

In [282]:
# transpose()
'''
参数说明
    input (Tensor): 需要转置的张量
    dim0 (int): 要转置的第一个维度
    dim1 (int): 要转置的第二个维度
    默认情况下，dim0 为 0，dim1 为 1，这意味着将第一个维度和第二个维度交换。
    可以使用 torch.transpose(input, dim0, dim1) 来指定要交换的维度。
'''
x = torch.arange(9).reshape(3, 3)
'''
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
       '''
'''
        [[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]
'''
print(x[:,0])
y = torch.transpose(x,1,0)
print(y)

z = x.t()

print(z)



















tensor([0, 3, 6])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([[0.5234, 0.4073],
        [0.4301, 0.2158],
        [0.4927, 0.9602]])
tensor([[0.5234, 0.4073],
        [0.4301, 0.2158],
        [0.4927, 0.9602]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [305]:
# 例如我们存在2个张量， 要讲他们相乘
a1 = torch.rand(2,3)
a2 = torch.rand(3,2)
print(a2)
a2 = torch.transpose(a2,0,1)
print(a2)
print(torch.multiply(a1,a2))


tensor([[0.0085, 0.1911],
        [0.2797, 0.2603],
        [0.7056, 0.1655]])
tensor([[0.0085, 0.2797, 0.7056],
        [0.1911, 0.2603, 0.1655]])
tensor([[0.0080, 0.1060, 0.3953],
        [0.0443, 0.1771, 0.1447]])


In [303]:
tt= torch.arange(1,25).reshape(2,3,4)
print(tt)

print(tt.shape)
tt1 = torch.transpose(tt,0,1)
print(tt1)
print(tt1.shape)
# tt2 = tt.permute(0,1,2)
#print(tt2)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
torch.Size([2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])
torch.Size([3, 2, 4])


#### 张量的元素运算(element-wise operation)
- 元素运算是对张量元素的运算，这些元素在张量中对应或具有相同的位置索引
- 两个张量必须有相同的形状才能执行元素操作

In [118]:
# 加法  
x = torch.tensor([[1,2,3],[1,2,3]])
y = torch.tensor([[2,3,4],[2,3,4]])
print(x+y)
print(torch.add(x,y))
# 支持广播
print(x+1)




tensor([[3, 5, 7],
        [3, 5, 7]])
tensor([[3, 5, 7],
        [3, 5, 7]])
tensor([[2, 3, 4],
        [2, 3, 4]])


In [119]:
# 减法
x = torch.tensor([[1,2,3],[1,2,3]])
y = torch.tensor([[2,3,4],[2,3,4]])
print(x-y)
print(torch.sub(x,y))
# 支持广播
print(y-2)

tensor([[-1, -1, -1],
        [-1, -1, -1]])
tensor([[-1, -1, -1],
        [-1, -1, -1]])
tensor([[0, 1, 2],
        [0, 1, 2]])


In [121]:
# 乘法
x = torch.tensor([[1,3,3],[2,2,4]])
y = torch.tensor([[2,3,4],[2,3,4]])
z = torch.tensor([[2,3,4],[2,3,4],[2,3,4]])
print(x * y )
print(torch.multiply(x,y))

print(torch.mm(x,z))
print(torch.matmul(x,z))


tensor([[ 2,  9, 12],
        [ 4,  6, 16]])
tensor([[ 2,  9, 12],
        [ 4,  6, 16]])
tensor([[14, 21, 28],
        [16, 24, 32]])
tensor([[14, 21, 28],
        [16, 24, 32]])


#### broadcast
- 规则
    - 两个张量在每个维度上至少有一个维度大小相同。
    - 较小张量在不改变数据的情况下，根据规则扩展到与较大张量相同形状。
    - 扩展后的两个张量进行逐元素运算。

- 广播机制只适用于形状兼容的张量。如果两个张量形状不匹配，则会抛出错误。
- 使用广播机制时，应注意数据类型是否兼容。
- 广播机制可能会降低计算效率，应尽量避免使用不必要的广播运算。

- 运算步骤
    - 标量与张量
      - 标量 5 与形状为 (2, 3) 的张量进行加法运算。
      - 标量 5 被扩展到与张量相同形状，即 (2, 3)。
      - 扩展后的标量与张量进行逐元素相加。
      - 最终结果为形状为 (2, 3) 的张量。
    - 部分维度相同的张量
      - 形状为 (2, 1) 的张量 A 与形状为 (2, 3) 的张量 B 进行加法运算。
      - 两个张量在第一维度上大小相同，因此在该维度上进行逐元素相加
      - 在第二维度上，张量 A 大小为 1，因此将其扩展到与张量 B 在该维度上相同大小，即 3。
      - 扩展后的张量 A 与张量 B 进行逐元素相加。
      

In [306]:
t=torch.rand(1)
t1 = torch.rand(2,1)
t2 = torch.rand(2,4)
t+t1
t1+t2

tensor([[1.0525, 1.7336, 1.5868, 0.9805],
        [0.7200, 0.5233, 0.1767, 0.4708]])

In [307]:
# 除法

x = torch.tensor([[8,10,12],[2,2,4]],requires_grad=True,dtype=torch.float)
y = torch.tensor([[2,5,4],[2,1,1]],requires_grad=True,dtype=torch.float)
print(x / y )


res = torch.div(x,y)

print(res)


print('Next Course')
loss = torch.nn.functional.binary_cross_entropy_with_logits(res,x)



loss.backward()
print(y.grad)
print(x.grad)

tensor([[4., 2., 3.],
        [1., 2., 4.]], grad_fn=<DivBackward0>)
tensor([[4., 2., 3.],
        [1., 2., 4.]], grad_fn=<DivBackward0>)
Next Course
tensor([[2.3393, 0.6079, 1.3809],
        [0.1057, 0.3731, 2.0120]])
tensor([[-1.2515, -0.6373, -0.9603],
        [-0.2724, -0.5199, -1.1697]])


#### Reduction operations -- 缩减操作

In [320]:
t= torch.arange(1,25).reshape(2,3,4)
t=t.to(torch.float)
t[0][0][2]=100
print(t)



# max value
print(torch.max(t,axis=1))
# max value index
print(torch.argmax(t))

# average 
print(torch.mean(t)) # 

# std standard deviation
print(torch.std(t))

# product all elements
 
print(torch.prod(t))

# find unique 
t2 = torch.tensor([[1,2],[3,4],[3,5]])
print(torch.unique(t2))

tensor([[[  1.,   2., 100.,   4.],
         [  5.,   6.,   7.,   8.],
         [  9.,  10.,  11.,  12.]],

        [[ 13.,  14.,  15.,  16.],
         [ 17.,  18.,  19.,  20.],
         [ 21.,  22.,  23.,  24.]]])
torch.return_types.max(
values=tensor([[  9.,  10., 100.,  12.],
        [ 21.,  22.,  23.,  24.]]),
indices=tensor([[2, 2, 0, 2],
        [2, 2, 2, 2]]))
tensor(2)
tensor(16.5417)
tensor(19.0240)
tensor(2.0682e+25)
tensor([1, 2, 3, 4, 5])


#### index

In [321]:
# index tensor1
t_s = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(t_s[2,3]) # line3,row4
print(t_s[2][3]) # modify line3,row4



tensor(12)
tensor(12)


In [330]:


# index tensor2
# vector
t_arr = list(range(10)) # create and array
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(t_arr[:]) # all elements
print(t_arr[1:4]) # from index 1 to index 4. (contains index1 , not contains index4)
print(t_arr[1:])# from index 1 to end. (contains index1 )
print(t_arr[:4]) # from index 0 to 4. (not contains index4 )
print(t_arr[:-1])# from index 0 to index(9-1) ( contains index(9-1))
print('****',t_arr[1:4:2]) # from index 1 to index 4. (contains index1 , not contains index4, step=2)

# 2d array
t_arr2 = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]) # create 2d array, 3rows 4cols
print(t_arr2[1:])  # from row index1 from end (include all cols)
print('####',t_arr2[1:3, 2:2]) # same as print(t_arr2[1:]) 
print(t_arr2[1:,1]) # second 2 cols of rows after row1
t_arr3=t_arr2[None]
print(t_arr3)
print(t_arr3.shape)




[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
**** [1, 3]
tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
#### tensor([], size=(2, 0), dtype=torch.int64)
tensor([ 6, 10])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])
torch.Size([1, 3, 4])


### 重写鱼书里的最简单版NN


In [332]:
import torch
import torch.functional as F
'''
This file is used for demo of the simplest neural network using Pytorch
see we have 2 inputs, 2 hidden layer, each hidden layer has 3 neurons, and 2 output
'''
# defien neural network weights and bias
def get_net_work_weights_bias():
    weights_bias = {}
    
    weights_bias['w1'] = torch.tensor([[0.1,0.3,0.4],[0.2,0.4,0.5]],dtype=torch.float32) # 2 inputs(input), 3 neurons
    weights_bias['b1'] = torch.tensor([0.1,0.1,0.1],dtype=torch.float32) # 3 neurons

    weights_bias['w2'] = torch.tensor([[0.1,0.2,0.3],[0.2,0.3,0.4],[0.4,0.5,0.6]],dtype=torch.float32) # 3 neurons(input), 3 neurons
    weights_bias['b2']= torch.tensor([0.2,0.2,0.2],dtype=torch.float32)# 3 neurons

    weights_bias['w3'] = torch.tensor([[0.1,0.2],[0.2,0.3],[0.4,0.3]],dtype=torch.float32)# 3 neurons(input), 2 output
    weights_bias['b3'] = torch.tensor([0.3,0.3],dtype=torch.float32)

    return weights_bias

def sigmoid(x):
    #return 1/(1+torch.exp(-x))
    # using torch functional sigmoid
    return torch.sigmoid(x)
def relu(x):
    return torch.relu(x)

def softmax(x):
    return torch.softmax(x,dim=0)

def forward(network,x):
    w1,w2,w3 = network['w1'],network['w2'],network['w3']
    b1,b2,b3 = network['b1'],network['b2'],network['b3']

    score1 = torch.matmul(x,w1)+b1 
    
    res1 = relu(score1)

    score2 = torch.matmul(res1,w2)+b2
    res2 = relu(score2)
    
    score3 = torch.matmul(res2,w3)+b3
    res3 = sigmoid(score3)
    return softmax(res3)

def main():
    network = get_net_work_weights_bias()
    x = torch.tensor([0.1,0.2],dtype=torch.float32)
    print(forward(network,x))

if __name__ == '__main__':
    main()



    




tensor([0.4983, 0.5017])


In [ ]:
torch.nn.init.kaimi