1. 花式索引 Fancy indexing

In [5]:
import numpy
a = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[[0,1,2],[0,1,2]]
print(b)

[1 5 9]


In [7]:
b = a.copy()
b[b>5]=0
print(b)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


2. 交换

In [189]:
x = 5
y = 6
z = 7
x, y, z = z, x, y
print(x,y,z)

7 5 6


3. 三目运算

In [14]:
outStr = "True" if True else "False"
print(outStr)

True


4. 链式比较

In [186]:
x = 2
if 4 > x > 1:
   print(x)
if 1 < x > 0:
   print(x)

2
2


5. 拆包 unpack

In [234]:
a,b,c = [1,2,3]
print(a,b,c)

a,b,c = (1,2,3)
print(a,b,c)

a,b,c = "123"
print(a,b,c)

a,b,c = 1,2,3
print(a,b,c)

a = 1,2,3
print(a)

1 2 3
1 2 3
1 2 3
1 2 3
(1, 2, 3)


In [236]:
def func():
    return 2,3
    
a ,b= func()

print(a,b)

2 3


In [48]:
a = b = c = 50
print(a,b,c)


50 50 50


In [69]:
a, b, c = [1,2,3,4]
print(a,b,c)

ValueError: too many values to unpack (expected 3)

In [ ]:
def func

In [215]:
a,_,c = 1,2,3
print(a,c)
print(_)

1 3
2


In [239]:
a, b, *c = [1,2,3,4]
print(a,b,c)

a, *b, c = (1,2,3,4)
print(a,b,c)

a, *_, _, c = [1,2,3,4]
print(a,_,_,c)

1 2 [3, 4]
1 [2, 3] 4
1 3 3 4


In [188]:
def func(a,b,c):
    print(a,b,c)

func(1,2,3)
func(*[1,2,3])
func(*(1,2,3))
func(*{"a":1,"b":2,"c":3})
func(**{"a":1,"c":2,"b":3})

1 2 3
1 2 3
1 2 3
a b c
1 3 2


In [202]:
a = {"a":1, "b":2}
b = {"b":3, "d":4}
{**a, **b}

{'a': 1, 'b': 3, 'd': 4}

In [221]:
def pack_test(a, b, **x):
    print(type(x), x)

def pack_test1(a, b, x):
    print(type(x), x)
    
pack_test(0, 0, one=1, two=2)
pack_test1(0, 0, dict(one=1, two=2))

def sum(a, b):
    return a + b

def f(**x):
    result = sum(**x)
    print(result)

f(a=1, b=2)

<class 'dict'> {'one': 1, 'two': 2}
<class 'dict'> {'one': 1, 'two': 2}
3


In [134]:
def f_withoutstar(a, b, args):
    print(type(args), args)
    print(*args)
 
def f_withstar(a, b, *args):
    print(type(args), args)
    print(*args)

f_withoutstar(0, 0, (1, 2, 3))
f_withstar(0, 0, 1, 2, 3)

<class 'tuple'> (1, 2, 3)
1 2 3
<class 'tuple'> (1, 2, 3)
1 2 3


6. for/esle

In [240]:
foo=[1,2,3,4,5]
for i in foo:
    if i == 1:
        break
else:
    print("未发现")

 

In [241]:
num = 1
sum_result = 0
 
# While loop to calculate the sum
while num <= 5:
    sum_result += num
    num += 1
else:
    print("Loop completed. Sum =", sum_result)

Loop completed. Sum = 15


In [218]:
for i, x in enumerate(foo):
    print(i, x)

0 1
1 2
2 3
3 4
4 5


In [77]:
print(list(enumerate(foo)))
print(list(enumerate(foo, 1)))


[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]
[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]


In [246]:
a = [1,2,3]
b = [4,5,6]
print(list(zip(a,b)))
a1,a2 =zip(*zip(a,b))
print(a1,a2)


[(1, 4), (2, 5), (3, 6)]
<class 'zip'>
(1, 2, 3) (4, 5, 6)


In [200]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
print(list(zip(a,b,c)))
a1,a2,a3 =zip(*zip(a,b,c))
print(a1,a2,a3)


[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
(1, 2, 3) (4, 5, 6) (7, 8, 9)


7. list

In [233]:
a = [1,2,3,4,5]
print(a[::-1])
print(a[::-2])

[5, 4, 3, 2, 1]
[5, 3, 1]


In [192]:
print(a[0:5:2])
print(a[1:3])

[1, 3, 5]
[2, 3]


In [193]:
print(9 in a)
print(9 not in a)
print(a * 2)
import numpy as np
list(np.array(a) * 2)

False
True
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


[2, 4, 6, 8, 10]

In [ ]:
python3 -m http.server

8. itertools

In [107]:
import itertools
for i in itertools.chain('good','bye','all'):
    print(i)

g
o
o
d
b
y
e
a
l
l


In [110]:
a = 'ABCDEFG'
b = [1,0,1]
c = itertools.compress(a, b)
for i in c:
    print(i, end=' ')   # A B E

A C 

In [111]:
a = [1,2,3,4,5,6,7,8,9]
b = itertools.dropwhile(lambda x: x<5, a)
c = itertools.dropwhile(lambda x: x>5, a)
for i in b:
    print(i, end=' ')    # 5 6 7 8 9
print()
for i in c:
    print(i, end=' ')    # 1 2 3 4 5 6 7 8 9

5 6 7 8 9 
1 2 3 4 5 6 7 8 9 

In [112]:
a = 'abc'
r = itertools.permutations(a)
for i in r:
    print(i)

('a', 'b', 'c')
('a', 'c', 'b')
('b', 'a', 'c')
('b', 'c', 'a')
('c', 'a', 'b')
('c', 'b', 'a')


In [114]:
a = 'abcde'
r = itertools.combinations(a,3)
for i in r:
    print(i)

('a', 'b', 'c')
('a', 'b', 'd')
('a', 'b', 'e')
('a', 'c', 'd')
('a', 'c', 'e')
('a', 'd', 'e')
('b', 'c', 'd')
('b', 'c', 'e')
('b', 'd', 'e')
('c', 'd', 'e')


9. match case

In [123]:
def http_error(status):
    match status:
        case 400:
            return 'Bad request'
        case 401:
            return 'Unauthorized'
        case 403:
            return 'Forbidden'
        case 404:
            return 'Not found'
        case _:
            return 'Unknown status code'

print(http_error(403))
print(http_error(500))

Forbidden
Unknown status code


In [122]:
def sequence(collection):
     match collection:
         case 1, [x, *others]:
             print(f"Got 1 and a nested sequence: {x=}, {others=}")
         case (1, x):
             print(f"Got 1 and {x}")
         case [x, y, z]:
             print(f"{x=}, {y=}, {z=}")

sequence([1, 2])
sequence([1, [2, 3]])
sequence([1, 2, 3])

Got 1 and 2
Got 1 and a nested sequence: x=2, others=[3]
x=1, y=2, z=3


In [121]:
def sequence2(collection):
     match collection:
         case ["a", *_, "z"]:
             print('matches any sequence of length two or more that starts with "a" and ends with "z".')
         case (_, _, *_):
             print('matches any sequence of length two or more.')
         case [*_]:
             print('matches a sequence of any length.')

sequence2(['a', 2, 3, 'z'])
sequence2(['a', 2, 3, 'b'])
sequence2(['a'])

matches any sequence of length two or more that starts with "a" and ends with "z".
matches any sequence of length two or more.
matches a sequence of any length.
